config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] ||
              request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  defaults = if Rails.env.test?
               { locale: :en }
             else
               {}
             end

  scope('(:locale)', locale: /#{I18n.available_locales.join('|')}/, defaults:) do
    root 'goals#index'

    get 'notifications/index', to: 'notifications#index', as: 'notifications'

    resource :calendar, only: :show, controller: :calendar
    resource :goal_tracking, controller: :goal_tracking
    resource :task_tracking, controller: :task_tracking

    # Chart
    resource :chart do
      member do
        get 'habit'
        get 'task'
      end
    end

    # Chart json data
    get '/habits_current_month_completions', to: 'charts#habits_current_month_completions_json'
    get '/tasks_chart', to: 'charts#tasks_json'
    get '/habits_chart', to: 'charts#habits_json'
    get '/habits_completions', to: 'charts#habits_completions_json'

    resources :challenges do
      member do
        get 'add_goal'
        post 'add_goal'

        get 'create_invitation'
        post 'create_invitation'
        get 'invite'
        patch 'confirm_invitation'
        patch 'decline_invitation'
        delete 'leave'
        delete 'destroy_goal'
        delete 'destroy_user'
      end
    end

    # Goals
    resources :goals do
      get '/habit_chart', to: 'charts#habit', as: 'habit_chart'
      get '/task_chart', to: 'charts#task', as: 'task_chart'
    end

    resources :goals do
      resources :habits, except: %i[show] do
        member do
          get 'complete'
        end
      end

      resources :tasks, except: %i[show] do
        member do
          get 'complete'
        end
      end
    end

    resources :categories
    resources :tasks
    resources :habits

    # Users
    resources :users, except: :new do
      member do
        get :confirm_email
        delete :delete_image_attachment
      end
    end

    # Sign up
    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'

    # Log in
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'

    # Log out
    get 'logout', to: 'sessions#destroy'

    # Password reset
    resources :password_resets, only: %i[new create edit update]

    # Pages
    get 'home', to: 'pages#home'
    get 'about', to: 'pages#about'

    # Dashboard
    get 'dashboard', to: 'dashboard#show'

    resources :dashboard_tasks, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    resources :dashboard_habits, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    # Notifications
    get 'mark_notifications_as_read', to: 'application#mark_all_notifications_as_read'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :redirect_user

  # GET /dashboard
  #----------------------------------------------------------------------------
  def show
    @all_goals = current_user.goals
                             .order(complete: :asc)
    @all_tasks = filter_tasks
    @all_habits = filter_habits
  end

  private

  def filter_tasks
    @tasks = current_user.tasks

    not_completed = @tasks.where(complete: false)

    if params.has_key?(:all_tasks)
      @tasks.order(complete: :desc)
    elsif params.has_key?(:open_tasks)
      not_completed
    else
      not_completed
    end
  end

  def filter_habits
    not_completed =
      Habit.not_completed_today(current_user)

    if params.has_key?(:all_habits)
      Habit.sorted_by_completion(current_user)
    elsif params.has_key?(:open_habits)
      not_completed
    else
      not_completed
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def calculate_tasks(user:, goal: nil)
    completed_tasks = user.tasks.where(complete: true)
    completed_tasks = completed_tasks.where(goal:) if goal
    completed_tasks = completed_tasks.count

    calculate_percentage(completed_tasks, 'tasks', goal:, user:)
  end

  def calculate_goals
    goals = current_user.goals
    completed = goals.where(complete: true).count

    calculate_percentage(completed, 'goals', user: current_user)
  end

  def calculate_habits
    completed_habits = current_user.habits.completed_today.count
    calculate_percentage(completed_habits, 'habits', user: current_user)
  end

  def calculate_percentage(completed_items, items, goal: nil, user: nil)
    user_items = user.send(items.to_sym)
    user_items = user_items.where(goal:) if goal
    total_items = user_items.count

    return total_items if total_items.zero?

    (completed_items.to_f / total_items * 100).round
  end
end

app/views/dashboard/show.html.erb
<% if @all_goals.empty? %>
  <div class="large-table-board mt-3">
    <%= render 'shared/empty', title: t('partials.empty.dashboard.title'),
                               message: t('partials.empty.dashboard.message'),
                               svg: true,
                               svg_path: 'icons/material/space_dashboard' %>
  </div>
<% else %>
  <section id="dashboard-show">
    <div class="actions-wrapper">
      <div class="goals-background">

        <div class="goals-wrapper">
          <ul class="goals-list">
            <% if @all_goals.present? %>
              <% @all_goals.each do |goal| %>

                <li class="goals-list__item" style="border: solid 5px <%= goal.color %>">
                  <div class="goals-list__title">
                    <%= goal.name.truncate(20) %>
                  </div>
                  <div class="divider"></div>

                  <div class="completed-wrapper completed-goal">
                    <%= link_with_icon 'arrow-up-square-fill', goal_path(goal) %>

                    <div class="progress-info">
                      <div class="progress-info__text">
                        <%= tasks_completed_for(goal) %>
                      </div>
                      <div>
                        <span><%= "#{calculate_tasks(goal:, user: current_user)}%" %></span>
                      </div>
                    </div>

                    <div class="progress-bar goal-bar">
                      <div class="progress-bar__progress" style="width: <%= calculate_tasks(goal:, user: current_user) %>%;"></div>
                    </div>
                  </div>
                </li>
              <% end %>
            <% else %>
              <span class="text-center fs-3">No Goals have yet</span>
            <% end %>
          </ul>
        </div>

        <div class="new_goal">
          <%= link_with_icon 'plus-lg', new_goal_path, 'new_goal', data: { turbo_frame: 'remote_modal' }, class: 'btn btn-primary btn-lg link-icon' %>
        </div>
      </div>


      <div class="action-items">
        <div class="action-items__header">
          <div class="action-items__title"><%= t('all_tasks') %></div>
            <%= link_with_icon 'plus-lg', new_dashboard_task_path, 'new_task', data: { turbo_frame: 'remote_modal' }, class: 'btn btn-primary btn-sm new-task link-icon' %>
        </div>

        <div class="divider"></div>

        <ul class="action-list">
          <% if @all_tasks.present? %>
            <% @all_tasks.each do |task| %>
              <li class="action-list__item">
                <%= task_complete_link(task, complete_dashboard_task_path(task)) %>
                <span><%= task.name %></span>
                <%= task.complete? ? icon('check-lg') : tag.i %>
              </li>
            <% end %>
          <% end %>
        </ul>

        <div class="completed-wrapper">
          <div class="progress-bar">
            <div class="progress-bar__progress" style="width: <%= calculate_tasks(goal: @goal, user: current_user) %>%;"></div>
          </div>

          <div class="completed-info">
            <div class="completed-info__text">
              <%= tasks_completed_for(current_user) %>
            </div>
          </div>

          <div class="completed-show">
            <% unless params[:all_tasks].present? %>
              <%= link_with_icon 'check-square', dashboard_path(all_tasks: 'all'), 'show', class: 'completed-show__all' %>
            <% else %>
              <%= link_with_icon 'check-square', dashboard_path(open_tasks: 'open'), 'hide', class: 'completed-show__all' %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="action-items">
        <div class="action-items__header">
          <div class="action-items__title"><%= t('all_habits') %></div>
            <%= link_with_icon 'plus-lg', new_dashboard_habit_path, 'new_habit', data: { turbo_frame: 'remote_modal' }, class: 'btn btn-primary btn-sm new-task link-icon' %>
        </div>

        <div class="divider"></div>

        <ul class="action-list">
          <% if @all_habits.present? %>
            <% @all_habits.each do |habit| %>
              <li class="action-list__item">
                <%= habit_complete_link(habit, complete_dashboard_habit_path(habit)) %>
                <span><%= habit.name %></span>
                <%= habit.completed_today? ? icon('check-lg') : tag.i %>
              </li>
            <% end %>
          <% end %>
        </ul>

        <div class="completed-wrapper">
          <div class="progress-bar">
            <div class="progress-bar__progress" style="width: <%= calculate_habits %>%;"></div>
          </div>

          <div class="completed-info">
            <div class="completed-info__text">
              <%= habits_completed_for(current_user) %>
            </div>
          </div>

          <div class="completed-show">
            <% unless params[:all_habits].present? %>
              <%= link_with_icon 'check-square', dashboard_path(all_habits: 'all'), 'show', class: 'completed-show__all' %>
            <% else %>
              <%= link_with_icon 'check-square', dashboard_path(open_habits: 'open'), 'hide', class: 'completed-show__all' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>