config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] ||
              request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  defaults = if Rails.env.test?
               { locale: :en }
             else
               {}
             end

  scope('(:locale)', locale: /#{I18n.available_locales.join('|')}/, defaults:) do
    root 'goals#index'

    get 'notifications/index', to: 'notifications#index', as: 'notifications'

    resource :calendar, only: :show, controller: :calendar
    resource :goal_tracking, controller: :goal_tracking
    resource :task_tracking, controller: :task_tracking

    # Chart
    resource :chart do
      member do
        get 'habit'
        get 'task'
      end
    end

    # Chart json data
    get '/habits_current_month_completions', to: 'charts#habits_current_month_completions_json'
    get '/tasks_chart', to: 'charts#tasks_json'
    get '/habits_chart', to: 'charts#habits_json'
    get '/habits_completions', to: 'charts#habits_completions_json'

    resources :challenges do
      member do
        get 'add_goal'
        post 'add_goal'

        get 'create_invitation'
        post 'create_invitation'
        get 'invite'
        patch 'confirm_invitation'
        patch 'decline_invitation'
        delete 'leave'
        delete 'destroy_goal'
        delete 'destroy_user'
      end
    end

    # Goals
    resources :goals do
      get '/habit_chart', to: 'charts#habit', as: 'habit_chart'
      get '/task_chart', to: 'charts#task', as: 'task_chart'
    end

    resources :goals do
      resources :habits, except: %i[show] do
        member do
          get 'complete'
        end
      end

      resources :tasks, except: %i[show] do
        member do
          get 'complete'
        end
      end
    end

    resources :categories
    resources :tasks
    resources :habits

    # Users
    resources :users, except: :new do
      member do
        get :confirm_email
        delete :delete_image_attachment
      end
    end

    # Sign up
    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'

    # Log in
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'

    # Log out
    get 'logout', to: 'sessions#destroy'

    # Password reset
    resources :password_resets, only: %i[new create edit update]

    # Pages
    get 'home', to: 'pages#home'
    get 'about', to: 'pages#about'

    # Dashboard
    get 'dashboard', to: 'dashboard#show'

    resources :dashboard_tasks, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    resources :dashboard_habits, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    # Notifications
    get 'mark_notifications_as_read', to: 'application#mark_all_notifications_as_read'
  end
end

app/controllers/goal_tracking_controller.rb
class GoalTrackingController < ApplicationController
  before_action :redirect_user

  helper_method :sort_column, :sort_direction

  # GET /goal_tracking
  #----------------------------------------------------------------------------
  def show
    @goals =
      if params[:search]
        Goal.search(params[:search], current_user, Goal.table_name)
      else
        current_user.goals.order("#{sort_column} #{sort_direction}")
      end
  end

  private

  def sort_column(column = 'deadline', model = 'goal')
    super
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/goal_tracking_helper.rb
module GoalTrackingHelper
end

app/views/goal_tracking/_table.html.erb
<table class="tracking">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th><%= t('name') %></th>
    <th><%= t('type') %></th>
    <th><%= sortable 'complete' %></th>
    <th><%= t('created_at') %></th>
    <th>
      <%= sortable 'deadline' %>
    <th><%= t('days_left.base') %></th>
  </tr>
  </thead>
  <tbody>
  <% items.each_with_index do |item, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= link_to item.name, item.instance_of?(Goal) ? item : item.goal, class: 'hover-link' %></td>
      <td><%= item.class.name %></td>
      <td>
        <% if item.complete? %>
          <span class="badge rounded-pill text-bg-success"><%= t('done') %></span>
        <% else %>
          <span class="badge rounded-pill text-bg-light"><%= t('in_process') %></span>
        <% end %>
      </td>
      <td><%= item.created_at&.strftime('%d-%m-%Y') %></td>
      <td><%= item.deadline&.strftime('%d-%m-%Y') %></td>
      <td><%= days_left(item) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/goal_tracking/show.html.erb
<div class="large-table-board mt-3" id="goal-tracking_show">
  <div class="table-header list"> 
    <h2 class="text-center title">
      <%= t('goals_tracker').upcase %>
    </h2>

    <div class="table-header__info">
      <div class="vr"></div>
      <%= goals_completed(@goals) %>
    </div>
  </div>

  <% if @goals.empty? %>
    <%= render 'shared/empty', title: t('partials.empty.tracking.title'),
                               message: t('partials.empty.tracking.goal_message'),
                               svg: true,
                               svg_path: 'icons/bootstrap/clipboard2-data' %>
  <% else %>
    <div class="large-table-board__body">
      <div class="buttons-list evenly">
        <div class="text-center my-3">
          <%= link_to t('switch_to_tasks'), task_tracking_path, class: 'btn btn-sm btn-primary' %>
        </div>

        <%= render 'layouts/search', path: goal_tracking_path %> 
      </div>

      <div class="tracking-wrapper table-body">
        <%= render 'goal_tracking/table', items: @goals %>
      </div>
    </div>
  <% end %>
</div>