config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] ||
              request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  defaults = if Rails.env.test?
               { locale: :en }
             else
               {}
             end

  scope('(:locale)', locale: /#{I18n.available_locales.join('|')}/, defaults:) do
    root 'goals#index'

    get 'notifications/index', to: 'notifications#index', as: 'notifications'

    resource :calendar, only: :show, controller: :calendar
    resource :goal_tracking, controller: :goal_tracking
    resource :task_tracking, controller: :task_tracking

    # Chart
    resource :chart do
      member do
        get 'habit'
        get 'task'
      end
    end

    # Chart json data
    get '/habits_current_month_completions', to: 'charts#habits_current_month_completions_json'
    get '/tasks_chart', to: 'charts#tasks_json'
    get '/habits_chart', to: 'charts#habits_json'
    get '/habits_completions', to: 'charts#habits_completions_json'

    resources :challenges do
      member do
        get 'add_goal'
        post 'add_goal'

        get 'create_invitation'
        post 'create_invitation'
        get 'invite'
        patch 'confirm_invitation'
        patch 'decline_invitation'
        delete 'leave'
        delete 'destroy_goal'
        delete 'destroy_user'
      end
    end

    # Goals
    resources :goals do
      get '/habit_chart', to: 'charts#habit', as: 'habit_chart'
      get '/task_chart', to: 'charts#task', as: 'task_chart'
    end

    resources :goals do
      resources :habits, except: %i[show] do
        member do
          get 'complete'
        end
      end

      resources :tasks, except: %i[show] do
        member do
          get 'complete'
        end
      end
    end

    resources :categories
    resources :tasks
    resources :habits

    # Users
    resources :users, except: :new do
      member do
        get :confirm_email
        delete :delete_image_attachment
      end
    end

    # Sign up
    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'

    # Log in
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'

    # Log out
    get 'logout', to: 'sessions#destroy'

    # Password reset
    resources :password_resets, only: %i[new create edit update]

    # Pages
    get 'home', to: 'pages#home'
    get 'about', to: 'pages#about'

    # Dashboard
    get 'dashboard', to: 'dashboard#show'

    resources :dashboard_tasks, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    resources :dashboard_habits, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    # Notifications
    get 'mark_notifications_as_read', to: 'application#mark_all_notifications_as_read'
  end
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id             :bigint           not null, primary key
#  recipient_type :string           not null
#  recipient_id   :bigint           not null
#  type           :string           not null
#  params         :jsonb
#  read_at        :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true

  after_create_commit :broadcast_notifications_list
  after_create_commit :broadcast_notifications_count
  after_create_commit :broadcast_notifications_count_header

  def recipient_unread_notifications
    Notification.includes(:recipient).where(recipient:).newest_first.unread
  end

  private

  # TODO - add feature tests
  def broadcast_notifications_list
    broadcast_append_to "notifications-list_#{recipient.id}",
                           target: "notifications-list_#{recipient.id}",
                           partial: 'layouts/notifications/notifications_list',
                           locals: { user: recipient, notifications: Notification.includes(:recipient).where(recipient:).newest_first.limit(20) }
  end

  def broadcast_notifications_count
    broadcast_replace_to "notifications-count",
                          target: "notifications-count",
                          partial: 'layouts/notifications/notifications_count',
                          locals: { current_user: recipient, unread: recipient_unread_notifications }
  end

  def broadcast_notifications_count_header
    broadcast_replace_to "notifications-count-header",
                          target: "notifications-count-header",
                          partial: 'layouts/notifications/notifications_count',
                          locals: { current_user: recipient, unread: recipient_unread_notifications }
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  TYPE_MAPPINGS = {
    'challenge_invite' => ChallengeUserNotification.name
  }.freeze

  def index
    @all_count = @notifications.count
    @read_count = @read.count
    @unread_count = @unread.count

    @type = TYPE_MAPPINGS[params[:filter]] || params[:filter]

    filter_notifications(params[:filter])

    mark_all_notifications_as_read
  end

  private

  def filter_notifications(filter)
    case filter
    when 'all'
      @notifications
    when 'read'
      @notifications = @read
    when 'unread'
      @notifications = @unread
    when 'challenge_invite'
      @notifications = @notifications.where(type: @type)
    end
  end

  def mark_all_notifications_as_read
    return if @unread.empty?

    @unread.mark_as_read!
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notif_limit(notif)
    notif >= 0 ? notif : '99+'
  end
end

app/views/notifications/index.html.erb
<div class="notifications-wrapper mt-3">
  <div class="list-group-wrapper">
    <div class="list-group">
      <%= active_link_to notifications_path(filter: 'all'), class: 'list-group-item list-group-item-action' do %>
        <%= 'All notifications' %>
        <%= tag.span notif_limit(@all_count), class: 'badge rounded-pill' unless @all_count.zero? %>
      <% end %>

      <%= active_link_to notifications_path(filter: 'unread'), class: 'list-group-item list-group-item-action' do %>
        <%= 'Unread' %>
        <%= tag.span notif_limit(@unread_count), class: 'badge rounded-pill badge_unread' unless @unread_count.zero? %> 
      <% end %>

      <%= active_link_to 'Read', notifications_path(filter: 'read'), class: 'list-group-item list-group-item-action' %>
    </div>

    <div class="list-group mt-3">
      <%= tag.span 'Filter by type', class: 'list-group-item list-group-item-action disabled title' %>
      <%= active_link_to 'Challege invitations', notifications_path(filter: 'challenge_invite'), class: 'list-group-item list-group-item-action' %>
    </div>
  </div>

  <div class="notifications" id="notifications_index">
    <header>
      <div class="notif-box">
        <h2 class="title"><%= t('notifications.common.notifications') %></h2>
        
        <p id="mark_all"><%= link_to t('notifications.common.mark_as_read'), mark_notifications_as_read_path %></p>
      </div>
    </header>

    <%= render 'layouts/notifications/notifications_list', notifications: @notifications, user: current_user %>
  </div>
</div>