config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] ||
              request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  defaults = if Rails.env.test?
               { locale: :en }
             else
               {}
             end

  scope('(:locale)', locale: /#{I18n.available_locales.join('|')}/, defaults:) do
    root 'goals#index'

    get 'notifications/index', to: 'notifications#index', as: 'notifications'

    resource :calendar, only: :show, controller: :calendar
    resource :goal_tracking, controller: :goal_tracking
    resource :task_tracking, controller: :task_tracking

    # Chart
    resource :chart do
      member do
        get 'habit'
        get 'task'
      end
    end

    # Chart json data
    get '/habits_current_month_completions', to: 'charts#habits_current_month_completions_json'
    get '/tasks_chart', to: 'charts#tasks_json'
    get '/habits_chart', to: 'charts#habits_json'
    get '/habits_completions', to: 'charts#habits_completions_json'

    resources :challenges do
      member do
        get 'add_goal'
        post 'add_goal'

        get 'create_invitation'
        post 'create_invitation'
        get 'invite'
        patch 'confirm_invitation'
        patch 'decline_invitation'
        delete 'leave'
        delete 'destroy_goal'
        delete 'destroy_user'
      end
    end

    # Goals
    resources :goals do
      get '/habit_chart', to: 'charts#habit', as: 'habit_chart'
      get '/task_chart', to: 'charts#task', as: 'task_chart'
    end

    resources :goals do
      resources :habits, except: %i[show] do
        member do
          get 'complete'
        end
      end

      resources :tasks, except: %i[show] do
        member do
          get 'complete'
        end
      end
    end

    resources :categories
    resources :tasks
    resources :habits

    # Users
    resources :users, except: :new do
      member do
        get :confirm_email
        delete :delete_image_attachment
      end
    end

    # Sign up
    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'

    # Log in
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'

    # Log out
    get 'logout', to: 'sessions#destroy'

    # Password reset
    resources :password_resets, only: %i[new create edit update]

    # Pages
    get 'home', to: 'pages#home'
    get 'about', to: 'pages#about'

    # Dashboard
    get 'dashboard', to: 'dashboard#show'

    resources :dashboard_tasks, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    resources :dashboard_habits, only: %i[new create] do
      member do
        get 'complete'
      end
    end

    # Notifications
    get 'mark_notifications_as_read', to: 'application#mark_all_notifications_as_read'
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  goal_id    :bigint
#  user_id    :bigint           not null
#
class Category < ApplicationRecord
  belongs_to :user

  has_many :goals

  validates :name, presence: true,
                   uniqueness: { scope: :user_id },
                   format: {
                     with: /\A\p{L}+\z/u,
                     message: :only_letters
                   },
                   length: {
                     minimum: 2,
                     maximum: 20
                   }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :redirect_user
  before_action :set_category, only: %i[show edit destroy]

  # GET /categories
  #----------------------------------------------------------------------------
  def index
    @categories = current_user.categories
  end

  # GET /categories/1
  #----------------------------------------------------------------------------
  def show; end

  # GET categories/new
  #----------------------------------------------------------------------------
  def new
    @category = Category.new
  end

  # GET /categories/1
  #----------------------------------------------------------------------------
  def edit; end

  # POST /categories
  #----------------------------------------------------------------------------
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        flash[:noticed] = t('.success')
        format.html { redirect_to goals_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  #----------------------------------------------------------------------------
  def destroy
    if @category.goals.any?
      flash[:danger] = t('.fail')
    else
      @category.destroy
      flash[:noticed] = t('.success')
    end

    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<div class="categories-wrapper">
  <div class="categories-wrapper__new">
    <%= link_with_icon 'plus-lg', new_category_path, 'new', data: { turbo_frame: 'remote_modal' }, class: 'btn btn-primary btn-sm link-icon' %>
    <%= link_with_icon 'list', categories_path, 'all', class: 'btn btn-primary btn-sm link-icon' %>
  </div>
  <div class="divider"></div>

  <div class="categories-wrapper__title"><%= t('all_categories') %></div>
  <div class="categories-wrapper__item all">
    <%= link_to t('all').capitalize, goals_path, class: 'bold-hover' %>
  </div>

  <ul class="categories-list">
    <% current_user.categories.each do |category| %>
      <li class="categories-list__item">
        <%= link_to category.name, goals_path(filter: category.id.to_s), 
                    class: "bold-hover #{'bold-active' if params[:filter].to_i == category.id.to_i}" %>
        <span><%= category.goals.count %></span>
      </li>
      <div class="divider"></div>
    <% end %>
  </ul>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |f| %>
  <%= render 'shared/error_messages', resource: category %>
  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-buttons">
    <%= link_to t('close'), '#', data: { bs_dismiss: 'modal' }, class: 'btn btn-secondary' %>
    <%= f.submit (category.new_record? ? t('create') : t('update')).to_s, class: 'btn btn-primary action' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/remote_modal', title: t('edit_category'), fade_in: true do %>
  <%= render 'form', category: @category %>
<% end %>

app/views/categories/form_update.turbo_stream.erb
<%= turbo_stream.update 'remote_modal' do %>
  <%= render 'shared/remote_modal', title: @category.new_record? ? t('new_category') : t('edit_category') do %>
    <%= render 'form', category: @category %>
  <% end %>
<% end %>

app/views/categories/index.html.erb
<div id="categories-index">
  <div class="categories-wrapper mt-3">
    <div class="action-items">
      <div class="action-items__header">
        <div class="action-items__title"><%= t('all_categories') %></div>
        
        <%= link_with_icon 'plus-lg', new_category_path, 'new_category', data: { turbo_frame: 'remote_modal' }, class: 'btn btn-primary btn-sm new-task link-icon' %>
      </div>

      <div class="divider"></div>

      <ul class="action-list">
        <% if @categories.present? %>
          <% @categories.each do |category| %>
            <li class="action-list__item">
              <span class="fw-bold"><%= category.name %></span>
              <div class="action-list__links">
                <%= link_with_icon 'pencil-square primary-icon', edit_category_path(category), class: 'icon-link' %>

                <%= delete_link_to '', category, 'trash danger-icon', title: 'delete_category_name', name: category.name %>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="buttons-list mt-3">
    <%= link_to t('back_to_goals'), goals_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'shared/remote_modal', title: t('new_category'), fade_in: true do %>
  <%= render 'form', category: @category %>
<% end %>

app/views/categories/show.html.erb
<h1 class="text-center"><%= @category.name %> category</h1> <!-- Is it really need? -->
<hr>

<div class="list-wrapper">
  <%= form_with url: goals_path, method: :get, class: 'text-center mb-3' do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search...',
                                                 class: 'input-group-text',
                                                 style: 'display: inline-block;' %>
    <%= submit_tag 'Search', class: 'btn btn-primary mb-1' %>
  <% end %>

  <div class="col-sm-12 col-md-12 box">
    <h2>Goals</h2>

    <ul>
      <% if @category.goals.present? %>
        <% @category.goals.each_with_index do |goal, index| %>
          <li class=""><span><%= index + 1 %></span><%= link_to goal.name,
                                                                [@category, goal] %>
          </li>
        <% end %>
      <% else %>
        <p class="text-center fs-4">No goals have yet</p>
      <% end %>
    </ul>
  </div>

  <div class="buttons-list mt-3">
    <%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary' %>
    <%= link_to 'Add Goal', new_category_goal_path(@category), class: 'btn btn-primary' %>
  </div>
</div>